@startuml
skinparam backgroundColor transparent
package "Existing System" {
[Existing Frontend] as ef
[Existing Backend]  as eb

}
package "Machine Learning Model"{
[Machine learning Model] as mlm
}
package "Depth System" {
[Backend] as b
() "api" as api
folder "Handlers" as handlers{
() "PostGIS" as postgis_handler
() "Current Depth map" as depth_handler
() "Neural Network" as cnn_handler
}

b -right- api
b -down- postgis_handler
b -down- depth_handler
b -down- cnn_handler
}

database "MariaDB"{
folder "Mission Properties"{
    ["Use Depth"] as ud
    ["Boat Depth"] as bd
    }
}



database "PostGIS" as postgis {
folder "Depth" {
[Calculated Areas] as ca
[Points] as points
}
}

cloud {
[Current depth Map] as cdm
[Aerial Images] as aerial
}


ef -right-> api
ef --> eb
eb --> ud
eb --> bd

postgis_handler --> ca
cnn_handler --> aerial
depth_handler --> cdm
postgis_handler --> points
mlm -up- cnn_handler
@enduml