@startuml
actor User
participant "Frontend" as F
participant "Backend" as B
database "Database" as D


group Prepare
    User -> F: Move Map
    activate F
    F -> B: Calculate area

    activate B
    B -> D: Request calculated areas
    activate D
    return Return calculated areas
    B -> B : Look which areas need to be calculated
    B -> B : Divide area into Points
    B -> D : Submit Points into Database
    activate D
    deactivate D
end
group Calculate
    B ->  D: Request not calculated points
    activate D
    return
        loop for Point in not calculated Points
            B ->B: Retrieve image from Point
            B ->B: Derive depth from image
            B ->D: Update point with depth
            activate D
            deactivate D
        end
end
group Visualize
    B ->  D: Request calculated points in area with a limit
    activate D
    return Return points as polygon
    return Transform polygon to GeoJSON
return Display areas deemed non-sailable
end



@enduml