@startuml
title MapResources
!startsub ImageTile
class ImageTile {
   +column: int
   +image: Any
   +row: int
   +level: int
   +layer_name: str
   +tile: Any

    - __init__(tile, layer_name, level, row, column, image=None)
    - read_and_save(lock=None)
    - save_image(lock)
    - get_image_from_tile(lock=None)
}
!endsub


class MapLayer{
    + already_splitted: bool
    + image_tiles: Set[ImageTile]
    + images_gotten: Set[tuple]
    + layer: str
    + level: int
    + name: str
    + original_layer: str
    + pixel_size: float
    + split: bool

    - __init__(name, layer, split)
    - add_image_gotten(image_tile)
    - add_image_tile(image_tile)
    - image_tile_in_layer(level, row, column)
    - get_image_tile(level, row, column)
    - clear_images()
}
class MapService {
    +ignore: bool
    +map_layers: List[MapLayer]
    +name: str
    +set_name: str
    +special_level: bool
    +tile_service: WebMapTileService
    +special_level: bool
    - __init__(json_object)
    - get_info(map_layer)
    - clear_images()
}

class MapResources {
    +standardized_rendering_pixel_size: float
    +web_maps: List[MapService]
    - __init__()
    - clear_images()
}
MapResources "1" *-right- "*" MapService
MapService "1" *-- "*" MapLayer
MapLayer "1" *-left- "*" ImageTile

@enduml